# @SI_Copyright@
# Copyright (c) 2006 - 2014 StackIQ Inc. All rights reserved.
#
# This product includes software developed by StackIQ Inc., these portions
# may not be modified, copied, or redistributed without the express written
# consent of StackIQ Inc.
# @SI_Copyright@

ROLLROOT = .

include $(PALLETBUILD)/etc/CCRolls.mk

bootstrap::
	yum -y install ./RPMS/dpkg-1.17.27-1.el7.x86_64.rpm
